#pragma once
#include "msl_prelude.h"
// Independently authored matrix types (MSL sections 2.3 and 3.2): floatNxM and
// halfNxM have N columns of floatM/halfM. Storage is an array of column vectors
// (column-major); m[c] is a column and m[c][r] an element. The compiler recognizes
// these declarations by their origin in this file and lowers constructors,
// indexing, operators and functions to typed IR itself; no member or operator has a body here.
namespace metal {
struct float2x2 {
  float2 columns[2];
  float2x2() = default;
  float2x2(const float2x2 &) = default;
  float2x2 &operator=(const float2x2 &) = default;
  explicit float2x2(float diagonal);
  float2x2(float2 column0, float2 column1);
  float2x2(float m00, float m01, float m10, float m11);
  float2 &operator[](int column);
  const float2 &operator[](int column) const;
  device float2 &operator[](int column) device;
  const device float2 &operator[](int column) const device;
  const constant float2 &operator[](int column) const constant;
  threadgroup float2 &operator[](int column) threadgroup;
  const threadgroup float2 &operator[](int column) const threadgroup;
};
struct float2x3 {
  float3 columns[2];
  float2x3() = default;
  float2x3(const float2x3 &) = default;
  float2x3 &operator=(const float2x3 &) = default;
  explicit float2x3(float diagonal);
  float2x3(float3 column0, float3 column1);
  float2x3(float m00, float m01, float m02, float m10, float m11, float m12);
  float3 &operator[](int column);
  const float3 &operator[](int column) const;
  device float3 &operator[](int column) device;
  const device float3 &operator[](int column) const device;
  const constant float3 &operator[](int column) const constant;
  threadgroup float3 &operator[](int column) threadgroup;
  const threadgroup float3 &operator[](int column) const threadgroup;
};
struct float2x4 {
  float4 columns[2];
  float2x4() = default;
  float2x4(const float2x4 &) = default;
  float2x4 &operator=(const float2x4 &) = default;
  explicit float2x4(float diagonal);
  float2x4(float4 column0, float4 column1);
  float2x4(float m00, float m01, float m02, float m03, float m10, float m11, float m12, float m13);
  float4 &operator[](int column);
  const float4 &operator[](int column) const;
  device float4 &operator[](int column) device;
  const device float4 &operator[](int column) const device;
  const constant float4 &operator[](int column) const constant;
  threadgroup float4 &operator[](int column) threadgroup;
  const threadgroup float4 &operator[](int column) const threadgroup;
};
struct float3x2 {
  float2 columns[3];
  float3x2() = default;
  float3x2(const float3x2 &) = default;
  float3x2 &operator=(const float3x2 &) = default;
  explicit float3x2(float diagonal);
  float3x2(float2 column0, float2 column1, float2 column2);
  float3x2(float m00, float m01, float m10, float m11, float m20, float m21);
  float2 &operator[](int column);
  const float2 &operator[](int column) const;
  device float2 &operator[](int column) device;
  const device float2 &operator[](int column) const device;
  const constant float2 &operator[](int column) const constant;
  threadgroup float2 &operator[](int column) threadgroup;
  const threadgroup float2 &operator[](int column) const threadgroup;
};
struct float3x3 {
  float3 columns[3];
  float3x3() = default;
  float3x3(const float3x3 &) = default;
  float3x3 &operator=(const float3x3 &) = default;
  explicit float3x3(float diagonal);
  float3x3(float3 column0, float3 column1, float3 column2);
  float3x3(float m00, float m01, float m02, float m10, float m11, float m12, float m20, float m21, float m22);
  float3 &operator[](int column);
  const float3 &operator[](int column) const;
  device float3 &operator[](int column) device;
  const device float3 &operator[](int column) const device;
  const constant float3 &operator[](int column) const constant;
  threadgroup float3 &operator[](int column) threadgroup;
  const threadgroup float3 &operator[](int column) const threadgroup;
};
struct float3x4 {
  float4 columns[3];
  float3x4() = default;
  float3x4(const float3x4 &) = default;
  float3x4 &operator=(const float3x4 &) = default;
  explicit float3x4(float diagonal);
  float3x4(float4 column0, float4 column1, float4 column2);
  float3x4(float m00, float m01, float m02, float m03, float m10, float m11, float m12, float m13, float m20, float m21, float m22, float m23);
  float4 &operator[](int column);
  const float4 &operator[](int column) const;
  device float4 &operator[](int column) device;
  const device float4 &operator[](int column) const device;
  const constant float4 &operator[](int column) const constant;
  threadgroup float4 &operator[](int column) threadgroup;
  const threadgroup float4 &operator[](int column) const threadgroup;
};
struct float4x2 {
  float2 columns[4];
  float4x2() = default;
  float4x2(const float4x2 &) = default;
  float4x2 &operator=(const float4x2 &) = default;
  explicit float4x2(float diagonal);
  float4x2(float2 column0, float2 column1, float2 column2, float2 column3);
  float4x2(float m00, float m01, float m10, float m11, float m20, float m21, float m30, float m31);
  float2 &operator[](int column);
  const float2 &operator[](int column) const;
  device float2 &operator[](int column) device;
  const device float2 &operator[](int column) const device;
  const constant float2 &operator[](int column) const constant;
  threadgroup float2 &operator[](int column) threadgroup;
  const threadgroup float2 &operator[](int column) const threadgroup;
};
struct float4x3 {
  float3 columns[4];
  float4x3() = default;
  float4x3(const float4x3 &) = default;
  float4x3 &operator=(const float4x3 &) = default;
  explicit float4x3(float diagonal);
  float4x3(float3 column0, float3 column1, float3 column2, float3 column3);
  float4x3(float m00, float m01, float m02, float m10, float m11, float m12, float m20, float m21, float m22, float m30, float m31, float m32);
  float3 &operator[](int column);
  const float3 &operator[](int column) const;
  device float3 &operator[](int column) device;
  const device float3 &operator[](int column) const device;
  const constant float3 &operator[](int column) const constant;
  threadgroup float3 &operator[](int column) threadgroup;
  const threadgroup float3 &operator[](int column) const threadgroup;
};
struct float4x4 {
  float4 columns[4];
  float4x4() = default;
  float4x4(const float4x4 &) = default;
  float4x4 &operator=(const float4x4 &) = default;
  explicit float4x4(float diagonal);
  float4x4(float4 column0, float4 column1, float4 column2, float4 column3);
  float4x4(float m00, float m01, float m02, float m03, float m10, float m11, float m12, float m13, float m20, float m21, float m22, float m23, float m30, float m31, float m32, float m33);
  float4 &operator[](int column);
  const float4 &operator[](int column) const;
  device float4 &operator[](int column) device;
  const device float4 &operator[](int column) const device;
  const constant float4 &operator[](int column) const constant;
  threadgroup float4 &operator[](int column) threadgroup;
  const threadgroup float4 &operator[](int column) const threadgroup;
};
// float operators: per-component sums and negation, scalar scaling, and products whose inner dimensions agree.
float2x2 operator+(float2x2 left, float2x2 right) __attribute__((annotate("msl.matrix:add")));
float2x2 operator-(float2x2 left, float2x2 right) __attribute__((annotate("msl.matrix:sub")));
float2x2 operator-(float2x2 value) __attribute__((annotate("msl.matrix:neg")));
float2x2 operator*(float2x2 left, float right) __attribute__((annotate("msl.matrix:mul")));
float2x2 operator*(float left, float2x2 right) __attribute__((annotate("msl.matrix:mul")));
float2 operator*(float2x2 left, float2 right) __attribute__((annotate("msl.matrix:mul")));
float2 operator*(float2 left, float2x2 right) __attribute__((annotate("msl.matrix:mul")));
float2x2 operator*(float2x2 left, float2x2 right) __attribute__((annotate("msl.matrix:mul")));
float3x2 operator*(float2x2 left, float3x2 right) __attribute__((annotate("msl.matrix:mul")));
float4x2 operator*(float2x2 left, float4x2 right) __attribute__((annotate("msl.matrix:mul")));
float2x3 operator+(float2x3 left, float2x3 right) __attribute__((annotate("msl.matrix:add")));
float2x3 operator-(float2x3 left, float2x3 right) __attribute__((annotate("msl.matrix:sub")));
float2x3 operator-(float2x3 value) __attribute__((annotate("msl.matrix:neg")));
float2x3 operator*(float2x3 left, float right) __attribute__((annotate("msl.matrix:mul")));
float2x3 operator*(float left, float2x3 right) __attribute__((annotate("msl.matrix:mul")));
float3 operator*(float2x3 left, float2 right) __attribute__((annotate("msl.matrix:mul")));
float2 operator*(float3 left, float2x3 right) __attribute__((annotate("msl.matrix:mul")));
float2x3 operator*(float2x3 left, float2x2 right) __attribute__((annotate("msl.matrix:mul")));
float3x3 operator*(float2x3 left, float3x2 right) __attribute__((annotate("msl.matrix:mul")));
float4x3 operator*(float2x3 left, float4x2 right) __attribute__((annotate("msl.matrix:mul")));
float2x4 operator+(float2x4 left, float2x4 right) __attribute__((annotate("msl.matrix:add")));
float2x4 operator-(float2x4 left, float2x4 right) __attribute__((annotate("msl.matrix:sub")));
float2x4 operator-(float2x4 value) __attribute__((annotate("msl.matrix:neg")));
float2x4 operator*(float2x4 left, float right) __attribute__((annotate("msl.matrix:mul")));
float2x4 operator*(float left, float2x4 right) __attribute__((annotate("msl.matrix:mul")));
float4 operator*(float2x4 left, float2 right) __attribute__((annotate("msl.matrix:mul")));
float2 operator*(float4 left, float2x4 right) __attribute__((annotate("msl.matrix:mul")));
float2x4 operator*(float2x4 left, float2x2 right) __attribute__((annotate("msl.matrix:mul")));
float3x4 operator*(float2x4 left, float3x2 right) __attribute__((annotate("msl.matrix:mul")));
float4x4 operator*(float2x4 left, float4x2 right) __attribute__((annotate("msl.matrix:mul")));
float3x2 operator+(float3x2 left, float3x2 right) __attribute__((annotate("msl.matrix:add")));
float3x2 operator-(float3x2 left, float3x2 right) __attribute__((annotate("msl.matrix:sub")));
float3x2 operator-(float3x2 value) __attribute__((annotate("msl.matrix:neg")));
float3x2 operator*(float3x2 left, float right) __attribute__((annotate("msl.matrix:mul")));
float3x2 operator*(float left, float3x2 right) __attribute__((annotate("msl.matrix:mul")));
float2 operator*(float3x2 left, float3 right) __attribute__((annotate("msl.matrix:mul")));
float3 operator*(float2 left, float3x2 right) __attribute__((annotate("msl.matrix:mul")));
float2x2 operator*(float3x2 left, float2x3 right) __attribute__((annotate("msl.matrix:mul")));
float3x2 operator*(float3x2 left, float3x3 right) __attribute__((annotate("msl.matrix:mul")));
float4x2 operator*(float3x2 left, float4x3 right) __attribute__((annotate("msl.matrix:mul")));
float3x3 operator+(float3x3 left, float3x3 right) __attribute__((annotate("msl.matrix:add")));
float3x3 operator-(float3x3 left, float3x3 right) __attribute__((annotate("msl.matrix:sub")));
float3x3 operator-(float3x3 value) __attribute__((annotate("msl.matrix:neg")));
float3x3 operator*(float3x3 left, float right) __attribute__((annotate("msl.matrix:mul")));
float3x3 operator*(float left, float3x3 right) __attribute__((annotate("msl.matrix:mul")));
float3 operator*(float3x3 left, float3 right) __attribute__((annotate("msl.matrix:mul")));
float3 operator*(float3 left, float3x3 right) __attribute__((annotate("msl.matrix:mul")));
float2x3 operator*(float3x3 left, float2x3 right) __attribute__((annotate("msl.matrix:mul")));
float3x3 operator*(float3x3 left, float3x3 right) __attribute__((annotate("msl.matrix:mul")));
float4x3 operator*(float3x3 left, float4x3 right) __attribute__((annotate("msl.matrix:mul")));
float3x4 operator+(float3x4 left, float3x4 right) __attribute__((annotate("msl.matrix:add")));
float3x4 operator-(float3x4 left, float3x4 right) __attribute__((annotate("msl.matrix:sub")));
float3x4 operator-(float3x4 value) __attribute__((annotate("msl.matrix:neg")));
float3x4 operator*(float3x4 left, float right) __attribute__((annotate("msl.matrix:mul")));
float3x4 operator*(float left, float3x4 right) __attribute__((annotate("msl.matrix:mul")));
float4 operator*(float3x4 left, float3 right) __attribute__((annotate("msl.matrix:mul")));
float3 operator*(float4 left, float3x4 right) __attribute__((annotate("msl.matrix:mul")));
float2x4 operator*(float3x4 left, float2x3 right) __attribute__((annotate("msl.matrix:mul")));
float3x4 operator*(float3x4 left, float3x3 right) __attribute__((annotate("msl.matrix:mul")));
float4x4 operator*(float3x4 left, float4x3 right) __attribute__((annotate("msl.matrix:mul")));
float4x2 operator+(float4x2 left, float4x2 right) __attribute__((annotate("msl.matrix:add")));
float4x2 operator-(float4x2 left, float4x2 right) __attribute__((annotate("msl.matrix:sub")));
float4x2 operator-(float4x2 value) __attribute__((annotate("msl.matrix:neg")));
float4x2 operator*(float4x2 left, float right) __attribute__((annotate("msl.matrix:mul")));
float4x2 operator*(float left, float4x2 right) __attribute__((annotate("msl.matrix:mul")));
float2 operator*(float4x2 left, float4 right) __attribute__((annotate("msl.matrix:mul")));
float4 operator*(float2 left, float4x2 right) __attribute__((annotate("msl.matrix:mul")));
float2x2 operator*(float4x2 left, float2x4 right) __attribute__((annotate("msl.matrix:mul")));
float3x2 operator*(float4x2 left, float3x4 right) __attribute__((annotate("msl.matrix:mul")));
float4x2 operator*(float4x2 left, float4x4 right) __attribute__((annotate("msl.matrix:mul")));
float4x3 operator+(float4x3 left, float4x3 right) __attribute__((annotate("msl.matrix:add")));
float4x3 operator-(float4x3 left, float4x3 right) __attribute__((annotate("msl.matrix:sub")));
float4x3 operator-(float4x3 value) __attribute__((annotate("msl.matrix:neg")));
float4x3 operator*(float4x3 left, float right) __attribute__((annotate("msl.matrix:mul")));
float4x3 operator*(float left, float4x3 right) __attribute__((annotate("msl.matrix:mul")));
float3 operator*(float4x3 left, float4 right) __attribute__((annotate("msl.matrix:mul")));
float4 operator*(float3 left, float4x3 right) __attribute__((annotate("msl.matrix:mul")));
float2x3 operator*(float4x3 left, float2x4 right) __attribute__((annotate("msl.matrix:mul")));
float3x3 operator*(float4x3 left, float3x4 right) __attribute__((annotate("msl.matrix:mul")));
float4x3 operator*(float4x3 left, float4x4 right) __attribute__((annotate("msl.matrix:mul")));
float4x4 operator+(float4x4 left, float4x4 right) __attribute__((annotate("msl.matrix:add")));
float4x4 operator-(float4x4 left, float4x4 right) __attribute__((annotate("msl.matrix:sub")));
float4x4 operator-(float4x4 value) __attribute__((annotate("msl.matrix:neg")));
float4x4 operator*(float4x4 left, float right) __attribute__((annotate("msl.matrix:mul")));
float4x4 operator*(float left, float4x4 right) __attribute__((annotate("msl.matrix:mul")));
float4 operator*(float4x4 left, float4 right) __attribute__((annotate("msl.matrix:mul")));
float4 operator*(float4 left, float4x4 right) __attribute__((annotate("msl.matrix:mul")));
float2x4 operator*(float4x4 left, float2x4 right) __attribute__((annotate("msl.matrix:mul")));
float3x4 operator*(float4x4 left, float3x4 right) __attribute__((annotate("msl.matrix:mul")));
float4x4 operator*(float4x4 left, float4x4 right) __attribute__((annotate("msl.matrix:mul")));
// float matrix functions (MSL section 6.6): transpose swaps the shape; determinant needs a square matrix.
float2x2 transpose(float2x2 value) __attribute__((annotate("msl.math:transpose")));
float determinant(float2x2 value) __attribute__((annotate("msl.math:determinant")));
float3x2 transpose(float2x3 value) __attribute__((annotate("msl.math:transpose")));
float4x2 transpose(float2x4 value) __attribute__((annotate("msl.math:transpose")));
float2x3 transpose(float3x2 value) __attribute__((annotate("msl.math:transpose")));
float3x3 transpose(float3x3 value) __attribute__((annotate("msl.math:transpose")));
float determinant(float3x3 value) __attribute__((annotate("msl.math:determinant")));
float4x3 transpose(float3x4 value) __attribute__((annotate("msl.math:transpose")));
float2x4 transpose(float4x2 value) __attribute__((annotate("msl.math:transpose")));
float3x4 transpose(float4x3 value) __attribute__((annotate("msl.math:transpose")));
float4x4 transpose(float4x4 value) __attribute__((annotate("msl.math:transpose")));
float determinant(float4x4 value) __attribute__((annotate("msl.math:determinant")));
struct half2x2 {
  half2 columns[2];
  half2x2() = default;
  half2x2(const half2x2 &) = default;
  half2x2 &operator=(const half2x2 &) = default;
  explicit half2x2(half diagonal);
  half2x2(half2 column0, half2 column1);
  half2x2(half m00, half m01, half m10, half m11);
  half2 &operator[](int column);
  const half2 &operator[](int column) const;
  device half2 &operator[](int column) device;
  const device half2 &operator[](int column) const device;
  const constant half2 &operator[](int column) const constant;
  threadgroup half2 &operator[](int column) threadgroup;
  const threadgroup half2 &operator[](int column) const threadgroup;
};
struct half2x3 {
  half3 columns[2];
  half2x3() = default;
  half2x3(const half2x3 &) = default;
  half2x3 &operator=(const half2x3 &) = default;
  explicit half2x3(half diagonal);
  half2x3(half3 column0, half3 column1);
  half2x3(half m00, half m01, half m02, half m10, half m11, half m12);
  half3 &operator[](int column);
  const half3 &operator[](int column) const;
  device half3 &operator[](int column) device;
  const device half3 &operator[](int column) const device;
  const constant half3 &operator[](int column) const constant;
  threadgroup half3 &operator[](int column) threadgroup;
  const threadgroup half3 &operator[](int column) const threadgroup;
};
struct half2x4 {
  half4 columns[2];
  half2x4() = default;
  half2x4(const half2x4 &) = default;
  half2x4 &operator=(const half2x4 &) = default;
  explicit half2x4(half diagonal);
  half2x4(half4 column0, half4 column1);
  half2x4(half m00, half m01, half m02, half m03, half m10, half m11, half m12, half m13);
  half4 &operator[](int column);
  const half4 &operator[](int column) const;
  device half4 &operator[](int column) device;
  const device half4 &operator[](int column) const device;
  const constant half4 &operator[](int column) const constant;
  threadgroup half4 &operator[](int column) threadgroup;
  const threadgroup half4 &operator[](int column) const threadgroup;
};
struct half3x2 {
  half2 columns[3];
  half3x2() = default;
  half3x2(const half3x2 &) = default;
  half3x2 &operator=(const half3x2 &) = default;
  explicit half3x2(half diagonal);
  half3x2(half2 column0, half2 column1, half2 column2);
  half3x2(half m00, half m01, half m10, half m11, half m20, half m21);
  half2 &operator[](int column);
  const half2 &operator[](int column) const;
  device half2 &operator[](int column) device;
  const device half2 &operator[](int column) const device;
  const constant half2 &operator[](int column) const constant;
  threadgroup half2 &operator[](int column) threadgroup;
  const threadgroup half2 &operator[](int column) const threadgroup;
};
struct half3x3 {
  half3 columns[3];
  half3x3() = default;
  half3x3(const half3x3 &) = default;
  half3x3 &operator=(const half3x3 &) = default;
  explicit half3x3(half diagonal);
  half3x3(half3 column0, half3 column1, half3 column2);
  half3x3(half m00, half m01, half m02, half m10, half m11, half m12, half m20, half m21, half m22);
  half3 &operator[](int column);
  const half3 &operator[](int column) const;
  device half3 &operator[](int column) device;
  const device half3 &operator[](int column) const device;
  const constant half3 &operator[](int column) const constant;
  threadgroup half3 &operator[](int column) threadgroup;
  const threadgroup half3 &operator[](int column) const threadgroup;
};
struct half3x4 {
  half4 columns[3];
  half3x4() = default;
  half3x4(const half3x4 &) = default;
  half3x4 &operator=(const half3x4 &) = default;
  explicit half3x4(half diagonal);
  half3x4(half4 column0, half4 column1, half4 column2);
  half3x4(half m00, half m01, half m02, half m03, half m10, half m11, half m12, half m13, half m20, half m21, half m22, half m23);
  half4 &operator[](int column);
  const half4 &operator[](int column) const;
  device half4 &operator[](int column) device;
  const device half4 &operator[](int column) const device;
  const constant half4 &operator[](int column) const constant;
  threadgroup half4 &operator[](int column) threadgroup;
  const threadgroup half4 &operator[](int column) const threadgroup;
};
struct half4x2 {
  half2 columns[4];
  half4x2() = default;
  half4x2(const half4x2 &) = default;
  half4x2 &operator=(const half4x2 &) = default;
  explicit half4x2(half diagonal);
  half4x2(half2 column0, half2 column1, half2 column2, half2 column3);
  half4x2(half m00, half m01, half m10, half m11, half m20, half m21, half m30, half m31);
  half2 &operator[](int column);
  const half2 &operator[](int column) const;
  device half2 &operator[](int column) device;
  const device half2 &operator[](int column) const device;
  const constant half2 &operator[](int column) const constant;
  threadgroup half2 &operator[](int column) threadgroup;
  const threadgroup half2 &operator[](int column) const threadgroup;
};
struct half4x3 {
  half3 columns[4];
  half4x3() = default;
  half4x3(const half4x3 &) = default;
  half4x3 &operator=(const half4x3 &) = default;
  explicit half4x3(half diagonal);
  half4x3(half3 column0, half3 column1, half3 column2, half3 column3);
  half4x3(half m00, half m01, half m02, half m10, half m11, half m12, half m20, half m21, half m22, half m30, half m31, half m32);
  half3 &operator[](int column);
  const half3 &operator[](int column) const;
  device half3 &operator[](int column) device;
  const device half3 &operator[](int column) const device;
  const constant half3 &operator[](int column) const constant;
  threadgroup half3 &operator[](int column) threadgroup;
  const threadgroup half3 &operator[](int column) const threadgroup;
};
struct half4x4 {
  half4 columns[4];
  half4x4() = default;
  half4x4(const half4x4 &) = default;
  half4x4 &operator=(const half4x4 &) = default;
  explicit half4x4(half diagonal);
  half4x4(half4 column0, half4 column1, half4 column2, half4 column3);
  half4x4(half m00, half m01, half m02, half m03, half m10, half m11, half m12, half m13, half m20, half m21, half m22, half m23, half m30, half m31, half m32, half m33);
  half4 &operator[](int column);
  const half4 &operator[](int column) const;
  device half4 &operator[](int column) device;
  const device half4 &operator[](int column) const device;
  const constant half4 &operator[](int column) const constant;
  threadgroup half4 &operator[](int column) threadgroup;
  const threadgroup half4 &operator[](int column) const threadgroup;
};
// half operators: per-component sums and negation, scalar scaling, and products whose inner dimensions agree.
half2x2 operator+(half2x2 left, half2x2 right) __attribute__((annotate("msl.matrix:add")));
half2x2 operator-(half2x2 left, half2x2 right) __attribute__((annotate("msl.matrix:sub")));
half2x2 operator-(half2x2 value) __attribute__((annotate("msl.matrix:neg")));
half2x2 operator*(half2x2 left, half right) __attribute__((annotate("msl.matrix:mul")));
half2x2 operator*(half left, half2x2 right) __attribute__((annotate("msl.matrix:mul")));
half2 operator*(half2x2 left, half2 right) __attribute__((annotate("msl.matrix:mul")));
half2 operator*(half2 left, half2x2 right) __attribute__((annotate("msl.matrix:mul")));
half2x2 operator*(half2x2 left, half2x2 right) __attribute__((annotate("msl.matrix:mul")));
half3x2 operator*(half2x2 left, half3x2 right) __attribute__((annotate("msl.matrix:mul")));
half4x2 operator*(half2x2 left, half4x2 right) __attribute__((annotate("msl.matrix:mul")));
half2x3 operator+(half2x3 left, half2x3 right) __attribute__((annotate("msl.matrix:add")));
half2x3 operator-(half2x3 left, half2x3 right) __attribute__((annotate("msl.matrix:sub")));
half2x3 operator-(half2x3 value) __attribute__((annotate("msl.matrix:neg")));
half2x3 operator*(half2x3 left, half right) __attribute__((annotate("msl.matrix:mul")));
half2x3 operator*(half left, half2x3 right) __attribute__((annotate("msl.matrix:mul")));
half3 operator*(half2x3 left, half2 right) __attribute__((annotate("msl.matrix:mul")));
half2 operator*(half3 left, half2x3 right) __attribute__((annotate("msl.matrix:mul")));
half2x3 operator*(half2x3 left, half2x2 right) __attribute__((annotate("msl.matrix:mul")));
half3x3 operator*(half2x3 left, half3x2 right) __attribute__((annotate("msl.matrix:mul")));
half4x3 operator*(half2x3 left, half4x2 right) __attribute__((annotate("msl.matrix:mul")));
half2x4 operator+(half2x4 left, half2x4 right) __attribute__((annotate("msl.matrix:add")));
half2x4 operator-(half2x4 left, half2x4 right) __attribute__((annotate("msl.matrix:sub")));
half2x4 operator-(half2x4 value) __attribute__((annotate("msl.matrix:neg")));
half2x4 operator*(half2x4 left, half right) __attribute__((annotate("msl.matrix:mul")));
half2x4 operator*(half left, half2x4 right) __attribute__((annotate("msl.matrix:mul")));
half4 operator*(half2x4 left, half2 right) __attribute__((annotate("msl.matrix:mul")));
half2 operator*(half4 left, half2x4 right) __attribute__((annotate("msl.matrix:mul")));
half2x4 operator*(half2x4 left, half2x2 right) __attribute__((annotate("msl.matrix:mul")));
half3x4 operator*(half2x4 left, half3x2 right) __attribute__((annotate("msl.matrix:mul")));
half4x4 operator*(half2x4 left, half4x2 right) __attribute__((annotate("msl.matrix:mul")));
half3x2 operator+(half3x2 left, half3x2 right) __attribute__((annotate("msl.matrix:add")));
half3x2 operator-(half3x2 left, half3x2 right) __attribute__((annotate("msl.matrix:sub")));
half3x2 operator-(half3x2 value) __attribute__((annotate("msl.matrix:neg")));
half3x2 operator*(half3x2 left, half right) __attribute__((annotate("msl.matrix:mul")));
half3x2 operator*(half left, half3x2 right) __attribute__((annotate("msl.matrix:mul")));
half2 operator*(half3x2 left, half3 right) __attribute__((annotate("msl.matrix:mul")));
half3 operator*(half2 left, half3x2 right) __attribute__((annotate("msl.matrix:mul")));
half2x2 operator*(half3x2 left, half2x3 right) __attribute__((annotate("msl.matrix:mul")));
half3x2 operator*(half3x2 left, half3x3 right) __attribute__((annotate("msl.matrix:mul")));
half4x2 operator*(half3x2 left, half4x3 right) __attribute__((annotate("msl.matrix:mul")));
half3x3 operator+(half3x3 left, half3x3 right) __attribute__((annotate("msl.matrix:add")));
half3x3 operator-(half3x3 left, half3x3 right) __attribute__((annotate("msl.matrix:sub")));
half3x3 operator-(half3x3 value) __attribute__((annotate("msl.matrix:neg")));
half3x3 operator*(half3x3 left, half right) __attribute__((annotate("msl.matrix:mul")));
half3x3 operator*(half left, half3x3 right) __attribute__((annotate("msl.matrix:mul")));
half3 operator*(half3x3 left, half3 right) __attribute__((annotate("msl.matrix:mul")));
half3 operator*(half3 left, half3x3 right) __attribute__((annotate("msl.matrix:mul")));
half2x3 operator*(half3x3 left, half2x3 right) __attribute__((annotate("msl.matrix:mul")));
half3x3 operator*(half3x3 left, half3x3 right) __attribute__((annotate("msl.matrix:mul")));
half4x3 operator*(half3x3 left, half4x3 right) __attribute__((annotate("msl.matrix:mul")));
half3x4 operator+(half3x4 left, half3x4 right) __attribute__((annotate("msl.matrix:add")));
half3x4 operator-(half3x4 left, half3x4 right) __attribute__((annotate("msl.matrix:sub")));
half3x4 operator-(half3x4 value) __attribute__((annotate("msl.matrix:neg")));
half3x4 operator*(half3x4 left, half right) __attribute__((annotate("msl.matrix:mul")));
half3x4 operator*(half left, half3x4 right) __attribute__((annotate("msl.matrix:mul")));
half4 operator*(half3x4 left, half3 right) __attribute__((annotate("msl.matrix:mul")));
half3 operator*(half4 left, half3x4 right) __attribute__((annotate("msl.matrix:mul")));
half2x4 operator*(half3x4 left, half2x3 right) __attribute__((annotate("msl.matrix:mul")));
half3x4 operator*(half3x4 left, half3x3 right) __attribute__((annotate("msl.matrix:mul")));
half4x4 operator*(half3x4 left, half4x3 right) __attribute__((annotate("msl.matrix:mul")));
half4x2 operator+(half4x2 left, half4x2 right) __attribute__((annotate("msl.matrix:add")));
half4x2 operator-(half4x2 left, half4x2 right) __attribute__((annotate("msl.matrix:sub")));
half4x2 operator-(half4x2 value) __attribute__((annotate("msl.matrix:neg")));
half4x2 operator*(half4x2 left, half right) __attribute__((annotate("msl.matrix:mul")));
half4x2 operator*(half left, half4x2 right) __attribute__((annotate("msl.matrix:mul")));
half2 operator*(half4x2 left, half4 right) __attribute__((annotate("msl.matrix:mul")));
half4 operator*(half2 left, half4x2 right) __attribute__((annotate("msl.matrix:mul")));
half2x2 operator*(half4x2 left, half2x4 right) __attribute__((annotate("msl.matrix:mul")));
half3x2 operator*(half4x2 left, half3x4 right) __attribute__((annotate("msl.matrix:mul")));
half4x2 operator*(half4x2 left, half4x4 right) __attribute__((annotate("msl.matrix:mul")));
half4x3 operator+(half4x3 left, half4x3 right) __attribute__((annotate("msl.matrix:add")));
half4x3 operator-(half4x3 left, half4x3 right) __attribute__((annotate("msl.matrix:sub")));
half4x3 operator-(half4x3 value) __attribute__((annotate("msl.matrix:neg")));
half4x3 operator*(half4x3 left, half right) __attribute__((annotate("msl.matrix:mul")));
half4x3 operator*(half left, half4x3 right) __attribute__((annotate("msl.matrix:mul")));
half3 operator*(half4x3 left, half4 right) __attribute__((annotate("msl.matrix:mul")));
half4 operator*(half3 left, half4x3 right) __attribute__((annotate("msl.matrix:mul")));
half2x3 operator*(half4x3 left, half2x4 right) __attribute__((annotate("msl.matrix:mul")));
half3x3 operator*(half4x3 left, half3x4 right) __attribute__((annotate("msl.matrix:mul")));
half4x3 operator*(half4x3 left, half4x4 right) __attribute__((annotate("msl.matrix:mul")));
half4x4 operator+(half4x4 left, half4x4 right) __attribute__((annotate("msl.matrix:add")));
half4x4 operator-(half4x4 left, half4x4 right) __attribute__((annotate("msl.matrix:sub")));
half4x4 operator-(half4x4 value) __attribute__((annotate("msl.matrix:neg")));
half4x4 operator*(half4x4 left, half right) __attribute__((annotate("msl.matrix:mul")));
half4x4 operator*(half left, half4x4 right) __attribute__((annotate("msl.matrix:mul")));
half4 operator*(half4x4 left, half4 right) __attribute__((annotate("msl.matrix:mul")));
half4 operator*(half4 left, half4x4 right) __attribute__((annotate("msl.matrix:mul")));
half2x4 operator*(half4x4 left, half2x4 right) __attribute__((annotate("msl.matrix:mul")));
half3x4 operator*(half4x4 left, half3x4 right) __attribute__((annotate("msl.matrix:mul")));
half4x4 operator*(half4x4 left, half4x4 right) __attribute__((annotate("msl.matrix:mul")));
// half matrix functions (MSL section 6.6): transpose swaps the shape; determinant needs a square matrix.
half2x2 transpose(half2x2 value) __attribute__((annotate("msl.math:transpose")));
half determinant(half2x2 value) __attribute__((annotate("msl.math:determinant")));
half3x2 transpose(half2x3 value) __attribute__((annotate("msl.math:transpose")));
half4x2 transpose(half2x4 value) __attribute__((annotate("msl.math:transpose")));
half2x3 transpose(half3x2 value) __attribute__((annotate("msl.math:transpose")));
half3x3 transpose(half3x3 value) __attribute__((annotate("msl.math:transpose")));
half determinant(half3x3 value) __attribute__((annotate("msl.math:determinant")));
half4x3 transpose(half3x4 value) __attribute__((annotate("msl.math:transpose")));
half2x4 transpose(half4x2 value) __attribute__((annotate("msl.math:transpose")));
half3x4 transpose(half4x3 value) __attribute__((annotate("msl.math:transpose")));
half4x4 transpose(half4x4 value) __attribute__((annotate("msl.math:transpose")));
half determinant(half4x4 value) __attribute__((annotate("msl.math:determinant")));
}
